/** Starter compendium authoring data (also used for chargen fallbacks). */
export default {
  features: [
    {
      key: "ironbound-endurance",
      name: "Ironbound Endurance",
      description: "<p>You ignore the first level of exhaustion from forced march or heavy load.</p>",
    },
    {
      key: "skylark-grace",
      name: "Skylark Grace",
      description: "<p>You have Boon on Agility checks made to balance or escape bonds.</p>",
    },
    {
      key: "rootwalker-ward",
      name: "Rootwalker Ward",
      description: "<p>You have Boon on Resolve checks against fear effects.</p>",
    },
    {
      key: "vanguard-line",
      name: "Hold the Line",
      description: "<p>When you succeed on an Athletics check to resist being moved, allies within 5 ft gain +1 to their next defense (future combat).</p>",
    },
    {
      key: "wayfinder-path",
      name: "Pathfinder's Eye",
      description: "<p>You cannot become lost by mundane means; you always know which way is north.</p>",
    },
    {
      key: "artificer-tinker",
      name: "Tinker's Hands",
      description: "<p>You have Boon on Craft checks to repair or improvise devices.</p>",
    },
    {
      key: "bg-medic-kit",
      name: "Field Kit",
      description: "<p>You begin play with a healer's satchel (no magical healing in MVP).</p>",
    },
    {
      key: "bg-chronicler",
      name: "Recorded Lore",
      description: "<p>You have Boon on Lore checks about events you have personally witnessed.</p>",
    },
    {
      key: "bg-scoundrel",
      name: "Underworld Contacts",
      description: "<p>You have Boon on Deception when passing as a common criminal type.</p>",
    },
  ],
  ancestries: [
    {
      key: "ironbound",
      name: "Ironbound",
      description: "<p>Stocky folk with forge-tempered constitution.</p>",
      size: "med",
      speed: 25,
      abilityAdjustments: { mgt: 1, fin: 0, res: 2, ins: 0, foc: 0, pre: -1 },
      featureKeys: ["ironbound-endurance"],
    },
    {
      key: "skylark",
      name: "Skylark",
      description: "<p>Lithe people known for cliff-side eyries.</p>",
      size: "med",
      speed: 35,
      abilityAdjustments: { mgt: -1, fin: 2, res: 0, ins: 0, foc: 0, pre: 0 },
      featureKeys: ["skylark-grace"],
    },
    {
      key: "rootwalker",
      name: "Rootwalker",
      description: "<p>Forest-born guardians with deep calm.</p>",
      size: "med",
      speed: 30,
      abilityAdjustments: { mgt: 0, fin: 0, res: 1, ins: 0, foc: 1, pre: 0 },
      featureKeys: ["rootwalker-ward"],
    },
  ],
  classes: [
    {
      key: "vanguard",
      name: "Vanguard",
      description: "<p>Front-line defender who holds ground for allies.</p>",
      hitDie: 10,
      skillChoices: 2,
      skillPool: ["athletics", "endurance", "awareness", "influence", "resolve"],
      featureKeys: ["vanguard-line"],
    },
    {
      key: "wayfinder",
      name: "Wayfinder",
      description: "<p>Scout and guide skilled in survival and precision.</p>",
      hitDie: 8,
      skillChoices: 3,
      skillPool: ["agility", "stealth", "survival", "awareness", "lore", "craft"],
      featureKeys: ["wayfinder-path"],
    },
    {
      key: "artificer",
      name: "Artificer",
      description: "<p>Inventor and scholar of mundane mechanisms.</p>",
      hitDie: 8,
      skillChoices: 2,
      skillPool: ["lore", "craft", "awareness", "influence", "performance"],
      featureKeys: ["artificer-tinker"],
    },
  ],
  backgrounds: [
    {
      key: "field-medic",
      name: "Field Medic",
      description: "<p>You served in war camps stitching wounds without magic.</p>",
      trainedSkills: ["endurance", "awareness"],
      starterGear: "Healer's satchel, bandages, bone saw",
      featureKeys: ["bg-medic-kit"],
    },
    {
      key: "chronicler",
      name: "Chronicler",
      description: "<p>You document truth for guild archives.</p>",
      trainedSkills: ["lore", "performance"],
      starterGear: "Journal, ink, courtly clothes",
      featureKeys: ["bg-chronicler"],
    },
    {
      key: "reformed-scoundrel",
      name: "Reformed Scoundrel",
      description: "<p>Your past is useful, even when you regret it.</p>",
      trainedSkills: ["stealth", "deception"],
      starterGear: "Dark hood, lockpicks, 15 gp",
      featureKeys: ["bg-scoundrel"],
    },
  ],
};
