/** Starter compendium authoring data (also used for chargen fallbacks). */
export default {
  features: [
    {
      key: "ironbound-endurance",
      name: "Ironbound Endurance",
      description: "<p>You ignore the first level of exhaustion from forced march or heavy load.</p>",
    },
    {
      key: "skylark-grace",
      name: "Skylark Grace",
      description: "<p>You have Boon on Balance checks made to escape bonds or keep footing.</p>",
    },
    {
      key: "rootwalker-ward",
      name: "Rootwalker Ward",
      description: "<p>You have Boon on Sense Motive checks against fear effects.</p>",
    },
    {
      key: "vanguard-line",
      name: "Hold the Line",
      description: "<p>When you succeed on a Climb or Athletics check to resist being moved, allies within 5 ft gain +1 to their next defense (future combat).</p>",
    },
    {
      key: "wayfinder-path",
      name: "Pathfinder's Eye",
      description: "<p>You cannot become lost by mundane means; you always know which way is north.</p>",
    },
    {
      key: "artificer-tinker",
      name: "Tinker's Hands",
      description: "<p>You have Boon on Craft checks to repair or improvise devices.</p>",
    },
    {
      key: "bg-medic-kit",
      name: "Field Kit",
      description: "<p>You begin play with a healer's satchel (no magical healing in MVP).</p>",
    },
    {
      key: "bg-chronicler",
      name: "Recorded Lore",
      description: "<p>You have Boon on Profession checks about events you have personally witnessed.</p>",
    },
    {
      key: "bg-scoundrel",
      name: "Underworld Contacts",
      description: "<p>You have Boon on Bluff when passing as a common criminal type.</p>",
    },
  ],
  ancestries: [
    {
      key: "ironbound",
      name: "Ironbound",
      description: "<p>Stocky folk with forge-tempered constitution.</p>",
      size: "med",
      speed: 25,
      abilityAdjustments: { mgt: 1, agi: 0, vit: 2, mnd: 0, ins: 0, cha: -1 },
      featureKeys: ["ironbound-endurance"],
    },
    {
      key: "skylark",
      name: "Skylark",
      description: "<p>Lithe people known for cliff-side eyries.</p>",
      size: "med",
      speed: 35,
      abilityAdjustments: { mgt: -1, agi: 2, vit: 0, mnd: 0, ins: 0, cha: 0 },
      featureKeys: ["skylark-grace"],
    },
    {
      key: "rootwalker",
      name: "Rootwalker",
      description: "<p>Forest-born guardians with deep calm.</p>",
      size: "med",
      speed: 30,
      abilityAdjustments: { mgt: 0, agi: 0, vit: 1, mnd: 0, ins: 1, cha: 0 },
      featureKeys: ["rootwalker-ward"],
    },
  ],
  classes: [
    {
      key: "vanguard",
      name: "Vanguard",
      description: "<p>Front-line defender who holds ground for allies.</p>",
      hitDie: 10,
      skillPointsPerLevel: 2,
      skillChoices: 2,
      skillPool: ["climb", "concentration", "listen", "diplomacy", "senseMotive"],
      featureKeys: ["vanguard-line"],
    },
    {
      key: "wayfinder",
      name: "Wayfinder",
      description: "<p>Scout and guide skilled in survival and precision.</p>",
      hitDie: 8,
      skillPointsPerLevel: 6,
      skillChoices: 3,
      skillPool: ["hide", "moveSilently", "survival", "search", "spot", "craft"],
      featureKeys: ["wayfinder-path"],
    },
    {
      key: "artificer",
      name: "Artificer",
      description: "<p>Inventor and scholar of mundane mechanisms.</p>",
      hitDie: 8,
      skillPointsPerLevel: 4,
      skillChoices: 2,
      skillPool: ["spellcraft", "craft", "search", "perform", "useMagicDevice"],
      featureKeys: ["artificer-tinker"],
      casterProgression: "half",
      powerPool: "mana",
      spellcastingAbility: "mnd",
    },
  ],
  backgrounds: [
    {
      key: "field-medic",
      name: "Field Medic",
      description: "<p>You served in war camps stitching wounds without magic.</p>",
      trainedSkills: ["heal", "listen"],
      starterGear: "Healer's satchel, bandages, bone saw",
      featureKeys: ["bg-medic-kit"],
    },
    {
      key: "chronicler",
      name: "Chronicler",
      description: "<p>You document truth for guild archives.</p>",
      trainedSkills: ["profession", "perform"],
      starterGear: "Journal, ink, courtly clothes",
      featureKeys: ["bg-chronicler"],
    },
    {
      key: "reformed-scoundrel",
      name: "Reformed Scoundrel",
      description: "<p>Your past is useful, even when you regret it.</p>",
      trainedSkills: ["hide", "bluff"],
      starterGear: "Dark hood, lockpicks, 15 gp",
      featureKeys: ["bg-scoundrel"],
    },
  ],
};
